agnostic_nms: false
amp: true
augment: true
auto_augment: None
batch: 80
bgr: 0.0
box: 7.5
cache: ram
cfg: /home/arasul42@tntech.edu/image_detection/ensembling_to_uncertainty/TrainingResults/Train3/temp_config.yaml
classes: null
close_mosaic: 10
cls: 0.5
conf: null
copy_paste: 0.0
cos_lr: false
crop_fraction: 1.0
data: /home/arasul42@tntech.edu/image_detection/ensembling_to_uncertainty/data/subset_5.yaml
degrees: 0.0
deterministic: true
device: CUDA
dfl: 1.5
dnn: false
dropout: 0.0
dynamic: false
embed: null
epochs: 1
erasing: 0.4
exist_ok: true
fliplr: 0.5
flipud: 0.0
format: torchscript
fraction: 1.0
freeze: null
half: true
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.5
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
label_smoothing: 0.0
line_width: null
lr0: 0.001
lrf: 0.01
mask_ratio: 4
max_det: 300
mixup: 0.0
mode: train
model: yolov8s.pt
momentum: 0.937
mosaic: 1.0
multi_scale: false
name: train
nbs: 64
nms: false
opset: null
optimize: false
optimizer: Adam
overlap_mask: true
patience: 15
perspective: 0.001
plots: true
pose: 12.0
pretrained: true
profile: false
project: /home/arasul42@tntech.edu/image_detection/ensembling_to_uncertainty/TrainingResults/Train3
rect: false
resume: false
retina_masks: false
save: true
save_conf: false
save_crop: false
save_dir: /home/arasul42@tntech.edu/image_detection/ensembling_to_uncertainty/TrainingResults/Train3/train
save_frames: false
save_hybrid: false
save_json: false
save_period: -1
save_txt: false
scale: 0.5
seed: 0
shear: 0.01
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: false
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.1
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
workspace: 4
